name: Pull Request Changelog Check
# by setting `on: [pull_request]`, that means action will be trigger when PR is opened, synchronize, reopened.
# Add labeled and unlabeled events too.
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
jobs:

  build:
    name: Run Changelog Check
    runs-on: ubuntu-latest
    steps:

    - name: Check out the code
      uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r ./scripts/requirements.txt

    - name: Changelog check
      if: ${{ !(contains(github.event.pull_request.labels.*.name, 'kind/changelog-not-required') || contains(github.event.pull_request.labels.*.name, 'Design') || contains(github.event.pull_request.labels.*.name, 'Website') || contains(github.event.pull_request.labels.*.name, 'Documentation'))}}
      run: ./scripts/changelog.py --path ../changelogs/unreleased --check