name: Simulate Docker Image Creation
on: 
    push:

jobs:
  prepare:
    name: Prepare docker tags and labels
    # runs-on: ["self-hosted", "linux", "arm64", "unity-dev", "4-core"]
    runs-on: ["ubuntu-latest"]
    steps:
      - name: Set docker build args as json encoded list
        id: docker_build_args
        run: > # multi-line string
          build_args='["GO_VERSION=1.21.13", "ALPINE_VERSION=3.19"]'
          && echo "docker_build_args='$build_args'" >> $GITHUB_OUTPUT

      - name: get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DD    
    